models/Channel.php
<?php
namespace app\models;

use yii\db\ActiveRecord;
use yii\data\ArrayDataProvider;
use yii\web\NotFoundHttpException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class Channel extends ActiveRecord{
    //批量导入的文件
    public $importFile;
    //语言名
    public $languageName;
    //channel对应的图片
    public $thumbnail;
    
    const SCENARIO_ADD = 'add';
    const SCENARIO_UPDATE = 'update';
    const SCENARIO_IMPORT = 'import';
    /**
     * 设置模型对应表名
     * @return string
     */
    public static function tableName(){
        return 'channel';
    }
    
    /**
     * 自动更新创建时间和修改时间
     * {@inheritDoc}
     * @see \yii\base\Component::behaviors()
     */
    public function behaviors(){
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createTime',
                'updatedAtAttribute' => 'updateTime',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    
    /**
     * 设置表单验证规则
     * {@inheritDoc}
     * @see \yii\base\Model::rules()
     */
    public function rules(){
        return [
            [['channelName', 'channelIp', 'channelUrl', 'urlType', 'channelType', 'languageName'], 'required'],
            ['importFile', 'file', 'skipOnEmpty' => false, 'mimeTypes' => ['application/xml', 'text/xml'],'extensions' => ['xml'], 'maxSize' => 50*1024*1024],
            ['channelPic', 'required', 'on' => self::SCENARIO_UPDATE],
            [['channelName', 'channelIp', 'channelUrl'], 'trim'],
            ['channelName', 'string', 'length' => [3, 10]],
            ['channelName', 'unique'],
            ['channelIp', 'ip'],
            ['thumbnail', 'file', 'mimeTypes' => 'image/*', 'extensions' => ['jpg', 'png', 'gif'], 'maxSize' => 1024*1024],
            ['thumbnail', 'file', 'skipOnEmpty' => false, 'on' => self::SCENARIO_ADD],
        ];
    }
    /**
     * 设置不同场景下要验证的属性
     * {@inheritDoc}
     * @see \yii\base\Model::scenarios()
     */
    public function scenarios(){
        return [
            self::SCENARIO_ADD => ['channelName', 'channelIp', 'thumbnail', 'channelUrl', 'urlType', 'channelType', 'languageName'],
            self::SCENARIO_UPDATE => ['channelName', 'channelIp', 'channelPic', 'thumbnail', 'channelUrl', 'urlType', 'channelType', 'languageName'],
            self::SCENARIO_IMPORT => ['importFile'],
        ];
    }
    
    /**
     * 设置表单显示的名称
     * {@inheritDoc}
     * @see \yii\base\Model::attributeLabels()
     */
    public function attributeLabels(){
        return [
            'channelIp' => 'Channel IP Address',
            'channelPic' => 'Channel Picture Path'
        ];
    }
    /**
     * 根据channelId获取channel信息
     * @param int $channelId
     * @return \app\models\Channel|NULL
     */
    public static function findChannelById($channelId){
        if(($model = self::findOne($channelId)) !== null){
            return $model;
        }else{
            throw new NotFoundHttpException("The channel whose channelId is $channelId don't exist, please try the right way to access channel.");
        }
    }
    
    /**
     * 获取该channels对应的account（API实现getDirectoryChannel时用到）
     */
    public function getAccounts(){
        return $this->hasMany(AccountProduct::className(), ['productId' => 'productId'])
                ->via('products');
    }
    
    /**
     * 获取Channel的语言
     * @return ActiveQuery
     */
    public function getLanguage(){
        return $this->hasOne(Language::className(), ['languageId' => 'languageId']);
    }
    /**
     *  获取channel所在的产品包
     */
    public function getProducts(){
        return $this->hasMany(Product::className(), ['productId' => 'productId'])
                ->viaTable('product_channel', ['channelId' => 'channelId']);
    }
    /**
     * 获取channel所在的目录
     */
    public function getDirectories(){
        return $this->hasMany(Directory::className(), ['directoryId' => 'directoryId'])
                ->viaTable('channel_directory', ['channelId' => 'channelId']);
    }
    /**
     * 根据getProducts方法构建dataProvider
     * @return \yii\data\ArrayDataProvider
     */
    public function findProducts(){
        $productProvider = new ArrayDataProvider([
            'allModels' => $this->products,//自动调用getProducts方法
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort'=>[
                'attributes'=>[
                    'productName',
                ],
            ],
        ]);
        return $productProvider;
    }
    /**
     * 根据getDirectories方法构建dataProvider
     * @return \yii\data\ArrayDataProvider
     */
    public function findDirectories(){
        $directoryProvider = new ArrayDataProvider([
            'allModels' => $this->directories,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort'=>[
                'attributes'=>[
                    'directoryName',
                ],
            ]
        ]);
        return $directoryProvider;
    }
    /**
     * 设置在save前要进行的操作
     * {@inheritDoc}
     * @see \yii\db\BaseActiveRecord::beforeSave()
     */
    public function beforeSave($insert){
        if(!empty($this->thumbnail)){
            $this->channelPic = '/images/channels' . '/' . $this->thumbnail->baseName . '.' . $this->thumbnail->extension;
        }
        $this->languageId = $this->languageName;
        return parent::beforeSave($insert);
    }
}

views/admin/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Add Administrator';
$this->params['breadcrumbs'][] = ['label' => 'Administrator List', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'userName')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'realName')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'password')->passwordInput() ?>

<?= $form->field($model, 'rePassword')->passwordInput() ?>

<?= $form->field($model, 'email') ?>

<div class="form-group">
    <?= Html::submitButton('Add', ['class' => 'btn btn-success']) ?>
    <?= Html::a('Cancel', \Yii::$app->request->referrer, ['class' => 'btn btn-warning cancel']) ?>
</div>
<?php ActiveForm::end(); ?>
<?php 
    $this->registerJs("
        $(document).on('click', '.cancel', function(){
            window.history.back();
        });
    ");
?>

views/admin/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\base\Widget;
$this->title = 'Administrator List';
$this->params['breadcrumbs'][] = $this->title;
$types = [
    0 => 'genernal',
    1 => 'super',
];
?>
<p>
	<div class="btn-group">
    	<?= Html::a('Delete Selected', [''], ['class' => 'btn btn-danger delete-all', 'disabled' => 'disabled']) ?>
    	<span class="btn btn-default delete-num">0</span>
    </div>
    <?php 
        if(Yii::$app->user->identity->type == 0){
            echo Html::a('New Administrator', ['create'], ['class' => 'btn btn-success disabled']);
        }else {
            echo Html::a('New Administrator', ['create'], ['class' => 'btn btn-success']);
        }
    ?>
</p>
<?= GridView::widget([
    'options' => ['class' => 'gridview', 'style' => 'overflow:auto', 'id' => 'grid'],
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'pager' => [
        'firstPageLabel' => 'First Page',
        'lastPageLabel' => 'Last Page',
    ],
    'rowOptions' => function($model, $key, $index, $grid){
        return ['class' => $index % 2 == 0 ? 'label-white' : 'label-grey' ];
    },
    'columns' => [
        [
            'class' => 'yii\grid\CheckboxColumn',
            'name' => 'id',
            'checkboxOptions' => function ($model, $key, $index, $column){
                if(Yii::$app->user->identity->type == 0 || Yii::$app->user->identity->userName == $model->userName){
                    return ['disabled' => 'disabled'];
                }
                return [];
            },
            'headerOptions' => ['width' => '10'],
        ],
        [
            'class' => 'yii\grid\SerialColumn',
            'headerOptions' => ['width' => '10'],
        ],
        'userName',
        'realName',
        'email',
        [
            'attribute' => 'type',
            'value' => function($model){
                return $model->type ? 'super' : 'genernal';
            },
            'filter' => $types,
        ],
        'lastLoginTime',
        'createTime',
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Operations',
            'headerOptions' => ['width' => '90'],
            'template' => '{view}&nbsp;&nbsp;&nbsp;{update}&nbsp;&nbsp;&nbsp;{delete}',
            'buttons' => [
                'view' => function($url, $model, $key){
                return Html::a('<i class="glyphicon glyphicon-eye-open"></i>',
                    ['view', 'id' => $key],
                    ['title' => 'View']);
                },
                'update' => function($url, $model, $key){
                    if(Yii::$app->user->identity->type == 0) return '<i class="glyphicon glyphicon-pencil" style="color: gray;"></i>';
                    return Html::a('<i class="glyphicon glyphicon-pencil"></i>',
                    ['update', 'id' => $key],
                    ['title' => 'Update']);
                },
                'delete' => function($url, $model, $key){
                    if(Yii::$app->user->identity->type == 0 || Yii::$app->user->identity->userName == $model->userName) 
                        return '<i class="glyphicon glyphicon-trash" style="color: gray;"></i>';
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>',
                    ['delete', 'id' => $key],
                    ['title' => 'Delete',
                     'data' => ['confirm' => "Are you sure to delete administrator $model->realName?"],
                    ]);
                },
            ],
        ],
    ],
]); 
$this->registerJs("
$(document).on('click', '.gridview', function () {
    var keys = $('#grid').yiiGridView('getSelectedRows');
    if(keys.length>0){
        $('.delete-all').attr('disabled', false);
        $('.delete-num').html(keys.length);
        $('.delete-all').attr('href', 'index.php?r=admin/delete-all&keys='+keys);
    }else{
        $('.delete-all').attr('disabled', 'disabled');
        $('.delete-num').html(0);
        $('.delete-all').attr('href', '');
    }
});
$(document).on('click', '.delete-all', function(){
    if($(this).attr('disabled')){
        return false;
    }else{
        var num = $('.delete-num').html();
        if(!confirm('are you sure to delete these '+num+' adminstrators?')){
            return false;
        }
    }
});
");
?>
<p>
	<div class="btn-group">
    	<?= Html::a('Delete Selected', [''], ['class' => 'btn btn-danger delete-all', 'disabled' => 'disabled']) ?>
    	<span class="btn btn-default delete-num">0</span>
    </div>
    <?php 
        if(Yii::$app->user->identity->type == 0){
            echo Html::a('New Administrator', ['create'], ['class' => 'btn btn-success disabled']);
        }else {
            echo Html::a('New Administrator', ['create'], ['class' => 'btn btn-success']);
        }
    ?>
</p>

views/admin/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\assets\AppAsset;

AppAsset::register($this);
$this->title = 'Login';
?>
<?php $this->beginPage()?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
<meta charset="<?= Yii::$app->charset ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="images/iptv.ico" rel="icon" type="image/x-icon" />
<link href="images/iptv.ico" rel="shortcut icon" type="image/x-icon" />
    <?= Html::csrfMetaTags()?>
    <title>KuanHong IPTVM-<?= Html::encode($this->title) ?></title>
    <?php $this->head()?>
</head>
<body>
<?php $this->beginBody()?>

<div class="container">
		<div class="row">
			<div class="login-title">KuanHong IPTV Content Management System</div>
			<div class="col-md-iptv col-md-offset-iptv">
				<div class="login-panel panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">Please Login</h3>
					</div>
					<div class="panel-body">

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => [
            'class' => ''
        ],
        'fieldConfig' => [
            'template' => "<div class=\"\">{input}</div>\n<div class=\"\">{error}</div>"
        ]
    ]);
    ?>
<fieldset>
        <?= $form->field($model, 'userName', 
            ['template' => '<div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        {input}
            </div><div>{error}</div>'])->textInput(['autofocus' => true, 'placeholder' => 'username'])?>

        <?= $form->field($model, 'password',
            ['template' => '<div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        {input}
            </div><div>{error}</div>'])->passwordInput(['placeholder' => 'password'])?>

		<?= $form->field($model,'captcha', ['options' => ['class' => 'form-group']])->widget(yii\captcha\Captcha::className(),
		    [
		        'template' => '<div class="captcha"><div class="captcha-img">{image}</div><div class="captcha-input">{input}</div><div style="clear:both"></div> </div>',
		        'captchaAction'=>'admin/captcha',
		        'imageOptions'=>['alt'=>'click to change', 'style'=>'cursor:pointer'],
		        'options' => ['class' => 'form-control', 'placeholder' => 'verify code'],
		]);?>
		
        <?=$form->field($model, 'rememberMe')->checkbox()?>
        
		<div class="form-group">
			<div class="">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-full', 'name' => 'login-button'])?>
            </div>
		</div>
</fieldset>
    <?php ActiveForm::end(); ?>

 </div>
 
				</div>
				<div style="text-align:center;font-size:16px;font-weight:bold;color:gray;">Copyright © <?=date('Y'); ?> KuanHong Inc., All Right Reserved</div>
			</div>
		</div>
	</div>
<?php $this->endBody()?>
</body>
</html>
<?php $this->endPage()?>

views/admin/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = 'Update Administrator';
$this->params['breadcrumbs'][] = ['label' => 'Administrator List', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'realName')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'email') ?>

<div class="form-group">
    <?= Html::submitButton('Update', ['class' => 'btn btn-success']) ?>
    <?= Html::a('Cancel', \Yii::$app->request->referrer, ['class' => 'btn btn-warning cancel']) ?>
</div>
<?php ActiveForm::end(); ?>
<?php 
    $this->registerJs("
        $(document).on('click', '.cancel', function(){
            window.history.back();
        });
    ");
?>

views/admin/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\base\Widget;
$this->title = 'Administrator ' . $model->realName;
$this->params['breadcrumbs'][] = ['label' => 'Administrator List', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading" style="background-color: #eeeeee;">
				<h5 style="font-weight: bold;">Details</h5>
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="dataTable_wrapper">
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'userName',
                            'realName',
                            'email',
                            [
                                'attribute' => 'type',
                                'value' => $model->type ? 'Super Administrator' : 'Genernal Administrator',
                            ],
                            'lastLoginTime',
                            'createTime',
                            'updateTime',
                        ],
                    ]) ?>
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<p>
	<?= Html::a('Back to Administrator List', ['index'], ['class' => 'btn btn-primary']) ?>
    <?php
        if(Yii::$app->user->identity->type == 0){
            echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-warning disabled']);
            echo '&nbsp;';
        }else{
            echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-warning']);
            echo '&nbsp;';
        }
        if(Yii::$app->user->identity->type == 0  || Yii::$app->user->identity->userName == $model->userName){
            echo Html::a('Delete', ['delete', 'id' => $model->id], ['class' => 'btn btn-danger disabled']);
        }else {
            echo Html::a('Delete', ['delete', 'id' => $model->id], ['class' => 'btn btn-danger']);
        }
        $this->registerJs("
            $(document).on('click', '.btn-danger', function(){
                if(!confirm('are you sure to delete this administrator?')){
                    return false;
                }
            });
        ");
    ?>
</p>