models/Menu.php
<?php
namespace app\models;

use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\data\ArrayDataProvider;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class Menu extends ActiveRecord{
    //父menu名称
    public $parentName;
    //在分级获取菜单是需要（左侧菜单栏的显示）
    public $children;
    /**
     * 设置模型对应的表名
     * @return string
     */
    public static function tableName(){
        return 'menu';
    }
    
    /**
     * 自动更新创建时间和修改时间
     * {@inheritDoc}
     * @see \yii\base\Component::behaviors()
     */
    public function behaviors(){
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createTime',
                'updatedAtAttribute' => 'updateTime',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    
    /**
     * 设置验证规则
     * {@inheritDoc}
     * @see \yii\base\Model::rules()
     */
    public function rules(){
        return [
            [['menuName', 'route', 'showLevel', 'showOrder', 'icon'], 'required'],
            ['parentName', 'safe'],
            ['route', 'match', 'pattern'=>'/^(\/\S+\/\S+|javascript:void\(0\))$/', 'message' => 'please input with the prompt'],
            ['showLevel', 'integer', 'min' => 1, 'max' => 3, 'integerOnly' => true],
            ['showOrder', 'integer'],
        ];
    }
    /**
     * 根据id获取menu信息
     * @param int $id
     * @throws NotFoundHttpException
     * @return \app\models\Menu|NULL
     */
    public static function findMenuById($id){
        if(($model = self::findOne($id)) !== null){
            return $model;
        }else {
            throw new NotFoundHttpException("The menu whose id is $id don't exist, please try the right way to access menu.");
        }
    }
    
    /**
     * 与自身进行关联，查询父级的名称
     */
    public function getParentMenu(){
        return $this->hasOne(Menu::className(), ['id' => 'parentId'])
                ->from(Menu::tableName().' parentMenu');
    }
    /**
     * 获取menu下的所有子menu
     */
    public function getChildrenMenus(){
        return $this->hasMany(Menu::className(), ['parentId' => 'id'])
                ->from(Menu::tableName().' childrenMenus');
    }
    
    public function findChildrenMenus(){
        $childrenProvider = new ArrayDataProvider([
            'allModels' => $this->childrenMenus,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => [
                    'menuName',
                    'showLevel',
                    'showOrder',
                ],
            ],
        ]);
        return $childrenProvider;
    }
    
    /**
     * 获取menu表中所有的非第三级菜单名称，新增修改时用到
     */
    public function getMenuItems(){
        $items = $this->find()->select(['id','menuName'])->where('showLevel in (1,2)')->all();
        return ArrayHelper::map($items, 'id', 'menuName');
    }
    /**
     * 进行赋值操作
     * {@inheritDoc}
     * @see \yii\db\BaseActiveRecord::beforeSave($insert)
     */
    public function beforeSave($insert){
        if(empty($this->parentName)){
            $this->parentId = null;
        }else{
            $this->parentId = $this->parentName;
        }
        return parent::beforeSave($insert);
    }
    /**
     * 按级获取所有的菜单
     */
    public function getAllMenus(){
        $first_level = $this->find()->where(['showLevel'=>1])->orderBy(['showOrder'=>SORT_ASC])->all();
        foreach ($first_level as $fl){
            $second_level = $this->find()->where(['showLevel'=>2, 'parentId'=>$fl->id])->orderBy(['showOrder'=>SORT_ASC])->all();
            if(!empty($second_level)){
                foreach ($second_level as $sl){
                    $third_level = $this->find()->where(['showLevel'=>3, 'parentId'=>$sl->id])->orderBy(['showOrder'=>SORT_ASC])->all();
                    if(!empty($third_level)){
                        $sl['children'] = $third_level;
                    }
                }
                $fl['children'] = $second_level;
            }
        }
        return $first_level;
    }
}

controllers/MenuController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\MenuSearch;
use app\models\Menu;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\HttpException;

class MenuController extends Controller{
    
    /**
     * 设置访问权限
     * {@inheritDoc}
     * @see \yii\base\Component::behaviors()
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['get'],
                    'view' => ['get'],
                    'create' => ['get', 'post'],
                    'update' => ['get', 'post'],
                    'delete' => ['get'],
                ]
            ],
        ];
    }
    
    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    /**
     * Index Action
     * 显示所有的菜单
     * @return string
     */
    public function actionIndex(){
        $searchModel = new MenuSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('index',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * View Action
     * 查看指定菜单信息
     * @param int $id
     */
    public function actionView($id){
        $model = Menu::findMenuById($id);
        $childrenProvider = $model->findChildrenMenus();
        return $this->render('view',[
            'model' => $model,
            'childrenProvider' => $childrenProvider,
        ]);
    }
    
    /**
     * Create Action
     * 创建一个新的菜单
     * @return string
     */
    public function actionCreate(){
        $model = new Menu();
        if($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()){
            Yii::info("create menu $model->menuName", 'administrator');
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $menu_items = $model->getMenuItems();
        return $this->render('create',[
            'model' => $model,
            'menu_items' => $menu_items,
        ]);
    }
    /**
     * Update Action
     * 修改菜单的信息
     * @param int $id
     * @return string
     */
    public function actionUpdate($id){
        $model = Menu::findMenuById($id);
        if($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()){
            Yii::info("update menu $model->menuName", 'administrator');
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $menu_items = array_diff($model->getMenuItems(), $model->childrenMenus, [$model->id => $model->menuName]);
        $model->parentName = $model->parentId;
        return $this->render('update',[
            'model' => $model,
            'menu_items' => $menu_items,
        ]);
    }
    /**
     * 删除指定的菜单
     * @param int $id
     */
    public function actionDelete($id){
        $model = Menu::findMenuById($id);
        if(!empty($model->childrenMenus)){
            throw new HttpException(500, "you can't delete the menu that has sub menus.");
        }
        $model->delete();
        Yii::info("delete menu $model->menuName", 'administrator');
        return $this->redirect(['index']);
    }
}

views/menu/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Add Menu';
$this->params['breadcrumbs'][] = ['label' => 'Menu List', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'menuName')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'parentName')->dropDownList($menu_items, ['prompt' => 'Select...']) ?>

<?= $form->field($model, 'route')->textInput(['maxlength' => true, 'placeholder' => 'such as /site/index, if not, javascrip:void(0) is recommended']) ?>

<?= $form->field($model, 'showLevel')->textInput(['maxlength' => true, 'placeholder' => 'level should between 1 and 3']) ?>

<?= $form->field($model, 'showOrder')->textInput(['maxlength' => true, 'placeholder' => 'show order of the same level is [1,2,...]']) ?>

<?= $form->field($model, 'icon', ['template' => 
    '{label}
    <div class="input-group">
        {input}
        <span class="input-group-addon"><span id="menu-img" class="fa fa-dashboard fa-fw"></span></span>
    </div>
    {error}'])->textInput(['class' => 'form-control menu-text','maxlength' => true, 'placeholder' => 'fa fa-dashboard fa-fw']) ?>

<div class="form-group">
    <?= Html::submitButton('Add', ['class' => 'btn btn-success']) ?>
    <?= Html::a('Cancel', \Yii::$app->request->referrer, ['class' => 'btn btn-warning cancel']) ?>
</div>
<?php ActiveForm::end(); ?>
<?php 
    $this->registerJs("
        $('.menu-text').bind('input propertychange', function(){
    		$('#menu-img').removeClass().addClass($(this).val());
    	});
        $(document).on('click', '.cancel', function(){
            window.history.back();
        });
    ");
?>

views/menu/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\base\Widget;
$this->title = 'Menu List';
$this->params['breadcrumbs'][] = $this->title;
?>
<p>
    <?= Html::a('New Menu', ['create'], ['class' => 'btn btn-success']) ?>
</p>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'pager' => [
        'firstPageLabel' => 'First Page',
        'lastPageLabel' => 'Last Page',
    ],
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        'menuName',
        [
            'attribute' => 'parentName',
            'format' => 'raw',
            'value' => function($model){
                if(!empty($model->parentMenu)){
                    return Html::a($model->parentMenu->menuName, ['menu/view', 'id' => $model->parentId], ['title' => 'view']);
                }
            },
            'filter'=>Html::activeTextInput($searchModel, 'parentName',['class'=>'form-control']),
        ],
        'route',
        [
            'attribute' => 'showLevel',
            'headerOptions' => [
                'width' => 30,
            ],
        ],
        [
            'attribute' => 'showOrder',
            'headerOptions' => [
                'width' => 30,
            ],
        ],
        [
            'attribute' => 'icon',
            'value' => function($model){
                return '<span class="' . $model->icon . '"></span>';
            },
            'headerOptions' => [
                'width' => 40,
            ],
            'format' => 'html',
        ],

        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Operations',
            'headerOptions' => ['width' => '90'],
            'template' => '{view}&nbsp;&nbsp;&nbsp;{update}&nbsp;&nbsp;&nbsp;{delete}',
            'buttons' => [
                'update' => function($url, $model, $key){
                    return Html::a('<i class="glyphicon glyphicon-pencil"></i>',
                        ['update', 'id' => $key],
                        ['title' => 'Update']);
                },
                'delete' => function($url, $model, $key){
                    if(!empty($model->childrenMenus)) return '<i class="glyphicon glyphicon-trash" style="color: #gray;"></i>';
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>',
                    ['delete', 'id' => $key],
                    ['title' => 'Delete',
                        'class' => '',
                        'data' => ['confirm' => "are you sure to delete menu $model->menuName?",]
                    ]);
                },
            ],
        ],
    ],
]); ?>
<p>
    <?= Html::a('New Menu', ['create'], ['class' => 'btn btn-success']) ?>
</p>

views/menu/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Update Menu';
$this->params['breadcrumbs'][] = ['label' => 'Menu List', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'menuName')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'parentName')->dropDownList($menu_items, ['prompt' => 'Select...']) ?>

<?= $form->field($model, 'route')->textInput(['maxlength' => true, 'placeholder' => 'such as /site/index, if not, javascrip:void(0) is recommended']) ?>

<?= $form->field($model, 'showLevel')->textInput(['maxlength' => true, 'placeholder' => 'level should between 1 and 3']) ?>

<?= $form->field($model, 'showOrder')->textInput(['maxlength' => true, 'placeholder' => 'show order of the same level is [1,2,...]']) ?>

<?= $form->field($model, 'icon', ['template' => 
    '{label}
    <div class="input-group">
        {input}
        <span class="input-group-addon"><span id="menu-img" class="fa fa-dashboard fa-fw"></span></span>
    </div>
    {error}'])->textInput(['class' => 'form-control menu-text','maxlength' => true, 'placeholder' => 'fa fa-dashboard fa-fw']) ?>

<div class="form-group">
    <?= Html::submitButton('Update', ['class' => 'btn btn-success']) ?>
    <?= Html::a('Cancel', \Yii::$app->request->referrer, ['class' => 'btn btn-warning cancel']) ?>
</div>

<?php ActiveForm::end(); ?>
<?php 
    $this->registerJs("
        if($('.menu-text').val().length != 0){
    	   $('#menu-img').removeClass().addClass($('.menu-text').val());
        }
        $('.menu-text').bind('input propertychange', function(){
    		$('#menu-img').removeClass().addClass($(this).val());
    	});
        $(document).on('click', '.cancel', function(){
            window.history.back();
        });
    ");
?>

views/menu/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\base\Widget;
use yii\grid\GridView;
$this->title = 'Menu ' . $model->menuName;
$this->params['breadcrumbs'][] = ['label' => 'Menu List', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading" style="background-color: #eeeeee;">
				<h5 style="font-weight: bold;">Details</h5>
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="dataTable_wrapper">
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'menuName',
                            [
                                'attribute' => 'parentName',
                                'format' => 'raw',
                                'value' => empty($model->parentMenu) ? '(not set)' : Html::a($model->parentMenu->menuName, ['menu/view', 'id' => $model->parentId], ['title' => 'view']),
                            ],
                            'route',
                            'showLevel',
                            'showOrder',
                            [
                                'attribute' => 'icon',
                                'value' => $model->icon . '<span class="' . $model->icon . '"></span>',
                                'format' => 'html',
                            ],
                            'createTime',
                            'updateTime',
                        ],
                    ]) ?>
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading" style="background-color: #eeeeee;">
				<h5 style="font-weight: bold;">Children Menus Has</h5>
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="dataTable_wrapper">
					<?= GridView::widget([
                        'dataProvider' => $childrenProvider,
                        'pager' => [
                            'firstPageLabel' => 'First Page',
                            'lastPageLabel' => 'Last Page',
                        ],
					    'rowOptions' => function($model, $key, $index, $grid){
					         return ['class' => $index % 2 == 0 ? 'label-white' : 'label-grey' ];
					    },
                        'columns' =>[
                            [
                                'class' => 'yii\grid\SerialColumn',
                                'headerOptions' => ['width' => '10'],
					        ],
                            [
                                'attribute'=>"menuName",
                                'format'=>'raw',
                                'value'=> function($model){
                                    //超链接
                                    return Html::a($model->menuName, ['menu/view', 'id' => $model->id], ['class' => 'profile-link','title' => 'view']);
                                }
                            ],
                            'showLevel',
                            'showOrder',
                            [
                                'attribute' => 'icon',
                                'value' => function($model){
                                    return '<span class="' . $model->icon . '"></span>';
                                },
                                'format' => 'html',
                            ],
                        ],
                      ]);
                    ?>
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<p>
	<?= Html::a('Back to Menu List', ['index'], ['class' => 'btn btn-primary']) ?>
    <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
    <?php 
        if(!empty($model->childrenMenus)){
            echo Html::a('Delete', ['delete', 'id' => $model->id], ['class' => 'btn btn-danger disabled']);
        }else{
            echo Html::a('Delete', ['delete', 'id' => $model->id], ['class' => 'btn btn-danger']);
        }
        $this->registerJs("
            $(document).on('click', '.btn-danger', function(){
                if(!confirm('are you sure to delete this menu?')){
                    return false;
                }
            });
        ");
    ?>
</p>